### ISSUE TITLE
Triangle::hasSharedEdge(Triangle* _t) doesn't correctly return true when two triangles share an edge

### ISSUE THREAD

**Issue by abbottjord94** [AgSwift-CS458-Project/SwiftAg-Library#5]
In a test with the following points and triangles:

Point 1:  (0,0,1)
Point 2: (5,0,1)
Point 3: (0,5,1)
Point 4: (5,5,1)

Tri 1: (Point 1, Point 2, Point 3)
Tri 2: (Point 2, Point 3, Point 4)

The shared edge between the two triangles should be the edge consisting of Points 2 and 3. However, the test for this case returns false. This may be an issue with the comparison function between points, edges, or both.

**Comment by mnemonicmnome** [comment]
Each triangle creates new edges, rather than adding pointers to already existing edges. This might also be contributing to our memory leak issue.

Not sure what the approach here is. First idea is use points as anchors for edges and allow triangles to ask points if an edge exists. From there the triangle can either create an edge or a reference to an existing edge.

Alternatively we can add checks for equivalency for edges and use an equivalency comparison. Duplicate edges is a bad solution, but that seems like a quicker fix.

**Comment by abbottjord94** [comment]
The edges in the Triangle class are created from pointers to already-existing Points. In theory, while the Edges are being duplicated, the newly-created Edges should be equivalent to any already-existing Edge. 

As it relates to the triangulation algorithms, however, it is the Triangles that are instantiated, not Edges.

**Comment by abbottjord94** [comment]
While working on this issue this morning, I discovered that not only is the Edge equality operator not working correctly, but neither is bool Point::operator==(Point* _p). This is probably the core of the problem with all of the other functions as well.

My best guess is that doubles can't be directly compared, even though they were initialized to the same values in my tests. We may need to change the data type for coordinate values to something like a 32-bit int, and use a scale factor in calculations.

**Comment by abbottjord94** [comment]
Fixed in PR #9 , closing.
